<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcliComunicazioni.Application\AcliComunicazioni.Application.csproj" />
    <ProjectReference Include="..\AcliComunicazioni.Domain\AcliComunicazioni.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
  </ItemGroup>

</Project>
